### ISSUE TITLE
Run command for docker not working

### ISSUE THREAD

**Issue by Paul-dH** [elkarbackup/elkarbackup-docker#17]
Hi,

I'm testing the docker image and I'm not aible to get the container working, if I run the command that's documented on the Dockerhub site:

`$ docker run --name my-elkarbackup --link some-mysql:mysql -d elkarbackup/elkarbackup:latest`

 I get: `docker: Error response from daemon: Could not get container for some-mysql.`

So I've changed the start command with the config below:

    docker run -d \
    --name elkarbackup \
    -p 8001:80 \
    -p 8101:443 \
    -e MYSQL_ROOT_PASSWORD="redacted" \
    -e EB_DB_PASSWORD="redacted" \
    -e EB_DB_USER="redacted-user" \
    -e EB_DB_USERPASSWORD="redacted" \
    -v /data/elkarbackup/config:/etc/elkarbackup \
    elkarbackup/elkarbackup:latest

But I keep getting a error: `MySQL is unavailable - sleeping`

How can I fix this?

**Comment by xezpeleta** [comment]
Hi @Paul-dH 

Did you fix your problem? I guess you also need to define EB_DB_HOST.

I usually run the container using docker-compose, so I probably should update the readme file.

**Comment by Paul-dH** [comment]
The problem on this issues was that I did'nt made a mysql container I think, I'm using the compose file now to create the setup. But there are some issues I can't resolve, I made a new issue for this.

A update on the readme would be greatly appreciated, great work! I really would like to give ElkarBackuk a try, it looks promising.

**Comment by Paul-dH** [comment]
Sorry for the delay, the fix works perfect!
