### ISSUE TITLE
Impossible to backup attached volumes 

### ISSUE THREAD

**Issue by launtony** [elkarbackup/elkarbackup-docker#19]
I need to backup the attached docker volumes (/etc/elkarbackup && /var/lib/elkarbackup/.ssh && /var/spool/elkarbackup) but I have an error (truncated :/). Currently I have excluded this path from my backup with elkarbackup :) 

Err : rsync incremental error..

**Comment by xezpeleta** [comment]
We have a completely new Docker image:

https://hub.docker.com/r/elkarbackup/elkarbackup/
