### ISSUE TITLE
timezone problem

### ISSUE THREAD

**Issue by ffabreti** [elkarbackup/elkarbackup-docker#24]
Hi, I'm running elkarbackup-docker 1.2.7.
My host is set to GMT-3
Some operations displays the correct time on logs (those initiated by me, in the web browser), but some are displaying GMT time, like scheduled jobs (they always start 3 hours earlier).
Here it is a image of the logs:
![screenshot - 17_08_2018 10_18_19](https://user-images.githubusercontent.com/2559032/44269770-e5e30300-a20b-11e8-9532-2f70869f63fb.jpg)

I am setting TZ and PHP_TZ on docker env variables. My docker run:
```
docker run \
--name=elkarbackup  \
--env="EB_DB_HOST=172.17.0.4" \
--env="MYSQL_ROOT_PASSWORD=my-great-password" \
--env="EB_VERSION=1.2.7" \
--volume="/xxx/xxx/elkarbackup/var-spool:/var/spool/elkarbackup" \
--volume="/xxx/xxx/elkarbackup/etc-elkarbackup:/etc/elkarbackup" \
--volume="/xxx/xxx/elkarbackup/var-lib-elkarbackup-.ssh:/var/lib/elkarbackup/.ssh" \
--network=bridge -p 4443:443 \
--link mysql-eb:mysql \
--restart=unless-stopped \
--detach=true \
--env="PHP_TZ=America/Sao_Paulo" \
--env="TZ=America/Sao_Paulo" \
-t elkarbackup/elkarbackup:latest
```

other commands:
```
# date
Fri Aug 17 10:58:11 BRT 2018
```
```
# docker exec -it elkarbackup php -i | grep -i -e "tz\|time\|zone"
...
date/time support => enabled
timelib version => 2016.02
"Olson" Timezone Database Version => 0.system
Timezone Database => internal
Default timezone => America/Sao_Paulo
date.timezone => no value => no value
MYSQL_ENV_TZ => America/Sao_Paulo
TZ => America/Sao_Paulo
PHP_TZ => America/Sao_Paulo
$_SERVER['MYSQL_ENV_TZ'] => America/Sao_Paulo
$_SERVER['TZ'] => America/Sao_Paulo
$_SERVER['PHP_TZ'] => America/Sao_Paulo
```
php script shows correct time of GMT-3:
```
# docker exec -it elkarbackup /bin/bash
# php -a
Interactive mode enabled

php > echo date('m/d/y h:m:s');
08/17/18 11:08:42
```

**Comment by xezpeleta** [comment]
@ffabreti sorry for the delay.

I'm gonna make TZ configurable, adding the necessary code in the entrypoint.

I'm gonna create a separate envvar for PHP (~TZ_PHP~ sorry, I mean PHP_TZ) which will default to TZ. Is that ok?

Thanks
