### ISSUE TITLE
Docker develpment wrong logic if bind volume

### ISSUE THREAD

**Issue by gpulido** [elkarbackup/elkarbackup-docker#25]
If the development version is used with a mount volume of ./src:/user/local/elkarbackup as the folder already exist (the docker mount systems needs the folder to exist) the installation of the elkarbackup is not done on the apache server.
The cause of this is the line 18 on the Entrypoint.sh where the installer is ONLY call if the folder EB_PATH doesn't exist. But that folder exist if it has being bound through docker_compose, so the entire install is not called. The problem is that the install also configures the apache server to work.
I think this is wrong, I would solve it, but I don't have the knowledge (yet) of docker to create my own docker container fork and also I don't know elkarbackup system to be sure that all is working properly.

**Comment by xezpeleta** [comment]
I'm closing this issue as the recommended docker image is the one with Apache: https://hub.docker.com/r/elkarbackup/elkarbackup/
