### ISSUE TITLE
Container does not start with SQLite

### ISSUE THREAD

**Issue by initrd** [elkarbackup/elkarbackup-docker#36]
`entrypoint.sh` only waits for the MySQL database to ping. The script should not attempt a ping if `SYMFONY__DATABASE__DRIVER` is set to `pdo_sqlite`

```
$ docker-compose logs -f
Attaching to elkarbackup_elkarbackup_1, elkarbackup_client_1
elkarbackup_1  | MySQL is unavailable - sleeping
elkarbackup_1  | MySQL is unavailable - sleeping
```

**Comment by redsil** [comment]
3 years and still not fixed :(

**Comment by elacunza** [comment]
Sorry, we only support Mysql/MariaDB. You're  welcome to contribute that support.
